import type {EditorThemeClasses} from 'lexical';

const editorTheme: EditorThemeClasses = {
    paragraph: 'lexical-paragraph',
    heading: {
        h1: 'markdown__heading markdown__heading--h1',
        h2: 'markdown__heading markdown__heading--h2',
        h3: 'markdown__heading markdown__heading--h3',
        h4: 'markdown__heading markdown__heading--h4',
        h5: 'markdown__heading markdown__heading--h5',
    },
    text: {
        bold: 'markdown__bold',
        italic: 'markdown__italic',
        strikethrough: 'markdown__strikethrough',
        code: 'markdown__code',
        underline: 'markdown__underline',
    },
    list: {
        ul: 'markdown__list markdown__list--ul',
        ol: 'markdown__list markdown__list--ol',
        listitem: 'markdown__list-item',
        nested: {
            listitem: 'markdown__nested-list-item',
        },
    },
    quote: 'markdown__quote',
    code: 'markdown__code-block',
    codeHighlight: {
        atrule: 'code-highlight-atrule',
        attr: 'code-highlight-attr',
        boolean: 'code-highlight-boolean',
        builtin: 'code-highlight-builtin',
        cdata: 'code-highlight-cdata',
        char: 'code-highlight-char',
        class: 'code-highlight-class',
        'class-name': 'code-highlight-class-name',
        comment: 'code-highlight-comment',
        constant: 'code-highlight-constant',
        deleted: 'code-highlight-deleted',
        doctype: 'code-highlight-doctype',
        entity: 'code-highlight-entity',
        function: 'code-highlight-function',
        important: 'code-highlight-important',
        inserted: 'code-highlight-inserted',
        keyword: 'code-highlight-keyword',
        namespace: 'code-highlight-namespace',
        number: 'code-highlight-number',
        operator: 'code-highlight-operator',
        prolog: 'code-highlight-prolog',
        property: 'code-highlight-property',
        punctuation: 'code-highlight-punctuation',
        regex: 'code-highlight-regex',
        selector: 'code-highlight-selector',
        string: 'code-highlight-string',
        symbol: 'code-highlight-symbol',
        tag: 'code-highlight-tag',
        url: 'code-highlight-url',
        variable: 'code-highlight-variable',
    },
    link: 'markdown__link',
    table: 'markdown__table',
    tableCell: 'markdown__table-cell',
    tableCellHeader: 'markdown__table-cell-header',
    tableRow: 'markdown__table-row',
};

export default editorTheme;
