#!/usr/bin/env bash
# renumber-migration.sh — okrbest DB 마이그레이션 재번호 도구
#
# 왜 필요한가:
#   okrbest는 000149 이후 자체 마이그레이션(알림 이력·조직 역할·직위·직책)을 끼워 넣어
#   upstream 대비 번호가 밀려 있다. 그래서 upstream 커밋을 cherry-pick하면 마이그레이션
#   번호가 우리 것과 충돌한다. 이 도구가 충돌한 신규 마이그레이션을 뒤로 밀어 정리한다.
#
# 사용법:
#   renumber-migration.sh status                        현재 번호 상태
#   renumber-migration.sh verify                        불변식 검사 (중복·짝·list 일치)
#   renumber-migration.sh sync-list                     migrations.list만 재생성
#   renumber-migration.sh plan [--base <ref>]           재번호 대상 탐지 (변경 없음)
#   renumber-migration.sh apply [--base <ref>] [--dry-run]   plan대로 재번호 + list 갱신
#   renumber-migration.sh renumber <old> <new> [--dry-run]   특정 번호 수동 재번호
#
#   --base <ref>  신규 파일 판별 기준 (기본 HEAD).
#                 cherry-pick을 이미 커밋했다면 --base HEAD~1.
#
# 전형적 흐름 (/speckit-sync 중):
#   git cherry-pick -x <hash>      # 마이그레이션 포함 커밋
#   renumber-migration.sh plan     # 무엇이 밀리는지 확인
#   renumber-migration.sh apply    # 재번호 + migrations.list 갱신
#   git add -A && git cherry-pick --continue

set -euo pipefail

REPO_ROOT="${REPO_ROOT:-$(git rev-parse --show-toplevel)}"
MIG_REL="server/channels/db/migrations"
MIG_ROOT="$REPO_ROOT/$MIG_REL"
LIST="$MIG_ROOT/migrations.list"

PY=python3
"$PY" -c '' >/dev/null 2>&1 || PY=python

die() { printf 'error: %s\n' "$1" >&2; exit 1; }

[[ -d "$MIG_ROOT" ]] || die "마이그레이션 디렉터리 없음: $MIG_ROOT"

# 현재 트리의 마이그레이션 파일 (migrations 하위 2단계 = dialect/파일)
tree_files() {
    find "$MIG_ROOT" -mindepth 2 -maxdepth 2 -name '*.sql' -printf '%P\n' 2>/dev/null | sort
}

# HEAD(또는 지정 ref)에 있던 마이그레이션 파일
base_files() {
    local ref="$1"
    git -C "$REPO_ROOT" ls-tree -r --name-only "$ref" -- "$MIG_REL" 2>/dev/null \
        | sed "s|^$MIG_REL/||" | grep -E '^[^/]+/.*\.sql$' | sort || true
}

# migrations.list 재생성 — server/Makefile의 migrations-extract 타깃과 동일하게
regen_list() {
    (
        cd "$REPO_ROOT/server"
        echo "# Autogenerated file to synchronize migrations sequence in the PR workflow, please do not edit." > channels/db/migrations/migrations.list
        find channels/db/migrations -maxdepth 2 -mindepth 2 | sort >> channels/db/migrations/migrations.list
    )
}

# 파일 이동 — 인덱스에 있으면 git mv, 아니면 plain mv
move_pair() {
    local dialect="$1" old="$2" new="$3" name="$4" dry="$5"
    local d
    for d in up down; do
        local from="$MIG_ROOT/$dialect/${old}_${name}.${d}.sql"
        local to="$MIG_ROOT/$dialect/${new}_${name}.${d}.sql"
        [[ -f "$from" ]] || continue
        if [[ "$dry" == "1" ]]; then
            printf '  [dry-run] %s/%s_%s.%s.sql → %s_%s.%s.sql\n' "$dialect" "$old" "$name" "$d" "$new" "$name" "$d"
        else
            git -C "$REPO_ROOT" mv "$MIG_REL/$dialect/${old}_${name}.${d}.sql" \
                                   "$MIG_REL/$dialect/${new}_${name}.${d}.sql" 2>/dev/null \
                || mv "$from" "$to"
            printf '  %s/%s_%s.%s.sql → %s_%s.%s.sql\n' "$dialect" "$old" "$name" "$d" "$new" "$name" "$d"
        fi
    done
}

# 코드에 남은 옛 번호 참조 보고 (마이그레이션 디렉터리 자신은 제외)
report_refs() {
    local nums="$1"
    local n hits found=0
    for n in $nums; do
        hits="$(grep -rIl --exclude-dir=node_modules --exclude-dir=.git "$n" \
                "$REPO_ROOT/server" 2>/dev/null | grep -v "$MIG_REL" || true)"
        if [[ -n "$hits" ]]; then
            if [[ $found -eq 0 ]]; then
                printf '\n옛 번호를 참조하는 파일 (수동 확인 필요):\n'
                found=1
            fi
            printf '  %s:\n' "$n"
            printf '    %s\n' $(printf '%s\n' "$hits" | sed "s|^$REPO_ROOT/||")
        fi
    done
}

# plan 계산 — dialect|old|new|name 형태로 출력
compute_plan() {
    local ref="$1"
    "$PY" - "$(tree_files)" "$(base_files "$ref")" <<'EOF'
import sys, re, collections

def parse(blob):
    out = []
    for line in blob.splitlines():
        line = line.strip()
        if not line:
            continue
        m = re.match(r'^([^/]+)/(\d{6})_(.+)\.(up|down)\.sql$', line)
        if m:
            out.append((m.group(1), m.group(2), m.group(3)))
    return out

tree = parse(sys.argv[1])
base = parse(sys.argv[2])

# (dialect, num, name) 단위로 중복 제거
tree_set = sorted(set(tree))
base_set = set(base)

# HEAD 기준 번호→이름 (dialect 무관하게 번호 점유로 본다)
base_names_by_num = collections.defaultdict(set)
for _, num, name in base_set:
    base_names_by_num[num].add(name)

max_base = max((int(n) for _, n, _ in base_set), default=0)

# 신규 도입분 = 트리에 있는데 base에 없는 것
newcomers = [t for t in tree_set if t not in base_set]

# 신규 도입분을 논리 단위((번호, 이름))로 모은다. 같은 마이그레이션의 여러 dialect는 한 단위.
dialects_of = collections.defaultdict(list)
for dialect, num, name in newcomers:
    if name in base_names_by_num.get(num, set()):
        continue                       # 같은 마이그레이션의 다른 dialect 추가 — 재번호 불필요
    dialects_of[(num, name)].append(dialect)

logical = sorted(dialects_of, key=lambda k: (int(k[0]), k[1]))

# 하나라도 base와 번호가 부딪히면 신규 도입분 '전체'를 뒤로 민다.
# 일부만 옮기면 upstream이 의도한 실행 순서가 뒤집힌다
# (예: thing@160·next@161이 들어올 때 thing만 165로 밀면 next가 먼저 실행된다).
collides = any(base_names_by_num.get(num) for num, _ in logical)

assignments = []
if collides:
    base_nums = {int(n) for _, n, _ in base_set}
    cursor = max_base
    for (num, name) in logical:
        cursor += 1
        while cursor in base_nums:
            cursor += 1
        new = f"{cursor:06d}"
        if new == num:
            continue                   # 제자리 — 옮길 필요 없음
        for dialect in dialects_of[(num, name)]:
            assignments.append(f"{dialect}|{num}|{new}|{name}")

print("\n".join(assignments))
EOF
}

cmd_status() {
    local nums max next_free count gaps
    nums="$(tree_files | grep -oE '^[^/]+/[0-9]{6}' | grep -oE '[0-9]{6}$' | sort -u)"
    count="$(printf '%s\n' "$nums" | grep -c . || true)"
    max="$(printf '%s\n' "$nums" | tail -1)"
    next_free="$("$PY" -c "
import sys
used={int(x) for x in '''$nums'''.split()}
n=max(used)+1
print(f'{n:06d}')
")"
    gaps="$("$PY" -c "
used={int(x) for x in '''$nums'''.split()}
lo,hi=min(used),max(used)
g=[f'{n:06d}' for n in range(lo,hi+1) if n not in used]
print(', '.join(g) if g else '없음')
")"
    printf '마이그레이션 %s개, 번호 범위 %s~%s\n' "$count" "$(printf '%s\n' "$nums" | head -1)" "$max"
    printf '다음 빈 번호: %s\n' "$next_free"
    printf '중간 빈 번호: %s\n' "$gaps"
    printf 'dialect: %s\n' "$(find "$MIG_ROOT" -mindepth 1 -maxdepth 1 -type d -printf '%f ' 2>/dev/null)"
}

cmd_verify() {
    local rc=0 out

    # 1. 번호 중복 (같은 번호에 다른 이름)
    out="$(tree_files | "$PY" -c "
import sys, re, collections
by=collections.defaultdict(set)
for l in sys.stdin:
    m=re.match(r'^([^/]+)/(\d{6})_(.+)\.(up|down)\.sql$', l.strip())
    if m: by[(m.group(1),m.group(2))].add(m.group(3))
for (d,n),names in sorted(by.items()):
    if len(names)>1:
        print(f'  {d}/{n}: {\", \".join(sorted(names))}')
")"
    if [[ -n "$out" ]]; then
        printf '번호 중복:\n%s\n' "$out"; rc=1
    fi

    # 2. up/down 짝
    out="$(tree_files | "$PY" -c "
import sys, re, collections
seen=collections.defaultdict(set)
for l in sys.stdin:
    m=re.match(r'^([^/]+)/(\d{6})_(.+)\.(up|down)\.sql$', l.strip())
    if m: seen[(m.group(1),m.group(2),m.group(3))].add(m.group(4))
for (d,n,name),kinds in sorted(seen.items()):
    if kinds != {'up','down'}:
        print(f'  {d}/{n}_{name}: {\", \".join(sorted(kinds))} 만 있음')
")"
    if [[ -n "$out" ]]; then
        printf 'up/down 짝 불완전:\n%s\n' "$out"; rc=1
    fi

    # 3. migrations.list 일치
    if [[ -f "$LIST" ]]; then
        local tmp
        tmp="$(mktemp)"
        (
            cd "$REPO_ROOT/server"
            echo "# Autogenerated file to synchronize migrations sequence in the PR workflow, please do not edit."
            find channels/db/migrations -maxdepth 2 -mindepth 2 | sort
        ) > "$tmp"
        if ! diff -q "$tmp" "$LIST" >/dev/null 2>&1; then
            printf 'migrations.list 불일치 — `make migrations-extract` 또는 이 도구의 apply 필요\n'
            diff "$LIST" "$tmp" | head -10 | sed 's/^/  /'
            rc=1
        fi
        rm -f "$tmp"
    else
        printf 'migrations.list 없음\n'; rc=1
    fi

    [[ $rc -eq 0 ]] && printf '정상 — 번호 중복 없음, up/down 짝 완전, migrations.list 일치\n'
    return $rc
}

cmd_plan() {
    local ref="${1:-HEAD}"
    local plan
    plan="$(compute_plan "$ref")"
    if [[ -z "$plan" ]]; then
        printf '재번호 대상 없음 (기준: %s)\n' "$ref"
        return 0
    fi
    printf '재번호 대상 (기준: %s):\n' "$ref"
    printf '%s\n' "$plan" | "$PY" -c "
import sys
for l in sys.stdin:
    l=l.strip()
    if not l: continue
    d,old,new,name=l.split('|')
    print(f'  {d}/{old}_{name}  →  {new}_{name}')
"
}

cmd_apply() {
    local ref="HEAD" dry=0
    while [[ $# -gt 0 ]]; do
        case "$1" in
            --base) ref="$2"; shift 2 ;;
            --dry-run) dry=1; shift ;;
            *) die "알 수 없는 인자: $1" ;;
        esac
    done

    local plan
    plan="$(compute_plan "$ref")"
    if [[ -z "$plan" ]]; then
        printf '재번호 대상 없음 (기준: %s)\n' "$ref"
        return 0
    fi

    printf '재번호 (기준: %s)%s:\n' "$ref" "$([[ $dry -eq 1 ]] && printf ' — dry-run')"
    local old_nums=""
    while IFS='|' read -r dialect old new name; do
        [[ -n "$dialect" ]] || continue
        move_pair "$dialect" "$old" "$new" "$name" "$dry"
        old_nums="$old_nums $old"
    done <<< "$plan"

    if [[ $dry -eq 1 ]]; then
        printf '\n(dry-run — 파일과 migrations.list를 바꾸지 않았다)\n'
        return 0
    fi

    regen_list
    printf '\nmigrations.list 갱신 완료\n'
    report_refs "$(printf '%s\n' $old_nums | sort -u | tr '\n' ' ')"
}

cmd_renumber() {
    local old="$1" new="$2" dry=0
    [[ "${3:-}" == "--dry-run" ]] && dry=1
    [[ "$old" =~ ^[0-9]{6}$ ]] || die "번호 형식이 아니다: $old"
    [[ "$new" =~ ^[0-9]{6}$ ]] || die "번호 형식이 아니다: $new"

    # new가 이미 쓰이는지
    if tree_files | grep -qE "^[^/]+/${new}_"; then
        die "이미 쓰는 번호다: $new"
    fi

    local found=0 dialect name
    while IFS= read -r f; do
        [[ "$f" =~ ^([^/]+)/${old}_(.+)\.up\.sql$ ]] || continue
        dialect="${BASH_REMATCH[1]}"; name="${BASH_REMATCH[2]}"
        found=1
        move_pair "$dialect" "$old" "$new" "$name" "$dry"
    done < <(tree_files)

    [[ $found -eq 1 ]] || die "해당 번호의 마이그레이션이 없다: $old"

    if [[ $dry -eq 1 ]]; then
        printf '(dry-run — 파일과 migrations.list를 바꾸지 않았다)\n'
        return 0
    fi
    regen_list
    printf 'migrations.list 갱신 완료\n'
    report_refs "$old"
}

usage() {
    sed -n '2,30p' "$0" | sed 's/^# \{0,1\}//'
}

cmd_sync_list() {
    regen_list
    printf 'migrations.list 재생성 완료 (server/Makefile의 migrations-extract와 동일)\n'
}

case "${1:-}" in
    status)    shift; cmd_status "$@" ;;
    verify)    shift; cmd_verify "$@" ;;
    sync-list) shift; cmd_sync_list "$@" ;;
    plan)     shift
              ref="HEAD"
              [[ "${1:-}" == "--base" ]] && { ref="$2"; shift 2; }
              cmd_plan "$ref" ;;
    apply)    shift; cmd_apply "$@" ;;
    renumber) shift; [[ $# -ge 2 ]] || die "사용법: renumber <old> <new> [--dry-run]"; cmd_renumber "$@" ;;
    ""|-h|--help|help) usage ;;
    *)        die "알 수 없는 명령: $1 (--help 참고)" ;;
esac
