#!/usr/bin/env bash
# renumber-migration.sh 테스트
#
# 실행: bash .specify/scripts/bash/tests/renumber-migration.test.sh
#
# 각 테스트는 임시 git 저장소에 마이그레이션 픽스처를 만들고 스크립트를 돌린다.
# 실제 저장소는 건드리지 않는다.

set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TARGET="$SCRIPT_DIR/renumber-migration.sh"

PASS=0
FAIL=0
CURRENT=""

fail() {
    printf '  ✗ %s\n    %s\n' "$CURRENT" "$1"
    FAIL=$((FAIL + 1))
}

ok() {
    printf '  ✓ %s\n' "$CURRENT"
    PASS=$((PASS + 1))
}

assert_eq() {
    local want="$1" got="$2" what="${3:-값}"
    if [[ "$want" == "$got" ]]; then return 0; fi
    fail "$what 불일치
      기대: $want
      실제: $got"
    return 1
}

assert_contains() {
    local haystack="$1" needle="$2"
    if [[ "$haystack" == *"$needle"* ]]; then return 0; fi
    fail "출력에 '$needle' 없음
      실제: $haystack"
    return 1
}

assert_file() {
    [[ -f "$1" ]] && return 0
    fail "파일 없음: $1"
    return 1
}

assert_no_file() {
    [[ ! -e "$1" ]] && return 0
    fail "파일이 남아 있음: $1"
    return 1
}

# 픽스처: server/channels/db/migrations/{postgres,mysql} 구조를 가진 임시 git 저장소
make_fixture() {
    local root
    root="$(mktemp -d)"
    mkdir -p "$root/server/channels/db/migrations/postgres"
    mkdir -p "$root/server/channels/db/migrations/mysql"
    (
        cd "$root"
        git init -q
        git config user.email t@t
        git config user.name t
    )
    printf '%s\n' "$root"
}

add_migration() {
    local root="$1" dialect="$2" num="$3" name="$4"
    printf -- '-- up %s\n' "$name" > "$root/server/channels/db/migrations/$dialect/${num}_${name}.up.sql"
    printf -- '-- down %s\n' "$name" > "$root/server/channels/db/migrations/$dialect/${num}_${name}.down.sql"
}

regen_list_fixture() {
    local root="$1"
    (
        cd "$root/server"
        echo "# Autogenerated file to synchronize migrations sequence in the PR workflow, please do not edit." > channels/db/migrations/migrations.list
        find channels/db/migrations -maxdepth 2 -mindepth 2 | sort >> channels/db/migrations/migrations.list
    )
}

commit_all() {
    local root="$1"
    (cd "$root" && git add -A && git commit -qm "fixture")
}

run() {
    local root="$1"; shift
    REPO_ROOT="$root" bash "$TARGET" "$@" 2>&1
}

# ─────────────────────────────────────────────────────────────
CURRENT="verify: 정상 픽스처를 통과시킨다"
{
    root="$(make_fixture)"
    add_migration "$root" postgres 000001 create_users
    add_migration "$root" postgres 000002 add_email
    regen_list_fixture "$root"
    commit_all "$root"

    out="$(run "$root" verify)"; rc=$?
    if assert_eq 0 "$rc" "종료 코드"; then ok; fi
    rm -rf "$root"
}

CURRENT="verify: 번호 중복을 잡아낸다"
{
    root="$(make_fixture)"
    add_migration "$root" postgres 000001 create_users
    add_migration "$root" postgres 000002 add_email
    add_migration "$root" postgres 000002 add_phone     # 중복 번호
    regen_list_fixture "$root"
    commit_all "$root"

    out="$(run "$root" verify)"; rc=$?
    if [[ $rc -eq 0 ]]; then
        fail "중복 번호를 통과시킴"
    else
        assert_contains "$out" "000002" && ok
    fi
    rm -rf "$root"
}

CURRENT="verify: up/down 짝이 없으면 잡아낸다"
{
    root="$(make_fixture)"
    add_migration "$root" postgres 000001 create_users
    rm "$root/server/channels/db/migrations/postgres/000001_create_users.down.sql"
    regen_list_fixture "$root"
    commit_all "$root"

    out="$(run "$root" verify)"; rc=$?
    if [[ $rc -eq 0 ]]; then
        fail "짝 없는 마이그레이션을 통과시킴"
    else
        assert_contains "$out" "000001" && ok
    fi
    rm -rf "$root"
}

CURRENT="verify: migrations.list 불일치를 잡아낸다"
{
    root="$(make_fixture)"
    add_migration "$root" postgres 000001 create_users
    regen_list_fixture "$root"
    add_migration "$root" postgres 000002 add_email     # list 갱신 안 함
    commit_all "$root"

    out="$(run "$root" verify)"; rc=$?
    if [[ $rc -eq 0 ]]; then
        fail "list 불일치를 통과시킴"
    else
        assert_contains "$out" "migrations.list" && ok
    fi
    rm -rf "$root"
}

CURRENT="status: 최고 번호와 다음 빈 번호를 보고한다"
{
    root="$(make_fixture)"
    add_migration "$root" postgres 000001 create_users
    add_migration "$root" postgres 000005 add_email
    regen_list_fixture "$root"
    commit_all "$root"

    out="$(run "$root" status)"
    assert_contains "$out" "000005" && assert_contains "$out" "000006" && ok
    rm -rf "$root"
}

CURRENT="plan: 신규 도입된 중복 번호를 재번호 대상으로 잡는다"
{
    root="$(make_fixture)"
    add_migration "$root" postgres 000001 create_users
    add_migration "$root" postgres 000002 our_feature
    regen_list_fixture "$root"
    commit_all "$root"

    # cherry-pick으로 upstream 마이그레이션이 들어온 상황
    add_migration "$root" postgres 000002 upstream_thing
    add_migration "$root" postgres 000003 upstream_next

    out="$(run "$root" plan)"
    assert_contains "$out" "upstream_thing" \
        && assert_contains "$out" "000003" \
        && assert_contains "$out" "000004" && ok
    rm -rf "$root"
}

CURRENT="plan: 재번호 대상이 없으면 그렇게 보고한다"
{
    root="$(make_fixture)"
    add_migration "$root" postgres 000001 create_users
    regen_list_fixture "$root"
    commit_all "$root"

    out="$(run "$root" plan)"; rc=$?
    assert_eq 0 "$rc" "종료 코드" && assert_contains "$out" "없" && ok
    rm -rf "$root"
}

CURRENT="apply --dry-run: 파일을 바꾸지 않는다"
{
    root="$(make_fixture)"
    add_migration "$root" postgres 000001 create_users
    add_migration "$root" postgres 000002 our_feature
    regen_list_fixture "$root"
    commit_all "$root"
    add_migration "$root" postgres 000002 upstream_thing

    run "$root" apply --dry-run >/dev/null
    assert_file "$root/server/channels/db/migrations/postgres/000002_upstream_thing.up.sql" \
        && assert_no_file "$root/server/channels/db/migrations/postgres/000003_upstream_thing.up.sql" \
        && ok
    rm -rf "$root"
}

CURRENT="apply: 중복 번호를 뒤로 밀고 상대 순서를 지킨다"
{
    root="$(make_fixture)"
    add_migration "$root" postgres 000001 create_users
    add_migration "$root" postgres 000002 our_feature
    regen_list_fixture "$root"
    commit_all "$root"

    add_migration "$root" postgres 000002 upstream_a
    add_migration "$root" postgres 000004 upstream_b

    run "$root" apply >/dev/null
    # upstream_a(원래 000002) → 000003, upstream_b(원래 000004) → 000004 유지 or 000004
    assert_file "$root/server/channels/db/migrations/postgres/000003_upstream_a.up.sql" \
        && assert_file "$root/server/channels/db/migrations/postgres/000003_upstream_a.down.sql" \
        && assert_no_file "$root/server/channels/db/migrations/postgres/000002_upstream_a.up.sql" \
        && assert_file "$root/server/channels/db/migrations/postgres/000004_upstream_b.up.sql" \
        && ok
    rm -rf "$root"
}

CURRENT="apply: migrations.list를 갱신한다"
{
    root="$(make_fixture)"
    add_migration "$root" postgres 000001 create_users
    add_migration "$root" postgres 000002 our_feature
    regen_list_fixture "$root"
    commit_all "$root"
    add_migration "$root" postgres 000002 upstream_a

    run "$root" apply >/dev/null
    list="$(cat "$root/server/channels/db/migrations/migrations.list")"
    assert_contains "$list" "postgres/000003_upstream_a.up.sql" \
        && { [[ "$list" != *"postgres/000002_upstream_a"* ]] || fail "list에 옛 번호가 남음"; } \
        && ok
    rm -rf "$root"
}

CURRENT="apply: 재번호 후 verify를 통과한다"
{
    root="$(make_fixture)"
    add_migration "$root" postgres 000001 create_users
    add_migration "$root" postgres 000002 our_feature
    regen_list_fixture "$root"
    commit_all "$root"
    add_migration "$root" postgres 000002 upstream_a

    run "$root" apply >/dev/null
    out="$(run "$root" verify)"; rc=$?
    assert_eq 0 "$rc" "verify 종료 코드" && ok
    rm -rf "$root"
}

CURRENT="apply: 여러 dialect의 같은 마이그레이션을 함께 옮긴다"
{
    root="$(make_fixture)"
    add_migration "$root" postgres 000001 create_users
    add_migration "$root" mysql    000001 create_users
    add_migration "$root" postgres 000002 our_feature
    regen_list_fixture "$root"
    commit_all "$root"

    add_migration "$root" postgres 000002 upstream_a
    add_migration "$root" mysql    000002 upstream_a

    run "$root" apply >/dev/null
    assert_file "$root/server/channels/db/migrations/postgres/000003_upstream_a.up.sql" \
        && assert_file "$root/server/channels/db/migrations/mysql/000003_upstream_a.up.sql" \
        && ok
    rm -rf "$root"
}

CURRENT="renumber: 지정한 번호를 직접 옮긴다"
{
    root="$(make_fixture)"
    add_migration "$root" postgres 000001 create_users
    add_migration "$root" postgres 000002 thing
    regen_list_fixture "$root"
    commit_all "$root"

    run "$root" renumber 000002 000009 >/dev/null
    assert_file "$root/server/channels/db/migrations/postgres/000009_thing.up.sql" \
        && assert_no_file "$root/server/channels/db/migrations/postgres/000002_thing.up.sql" \
        && ok
    rm -rf "$root"
}

CURRENT="renumber: 이미 쓰는 번호로는 옮기지 않는다"
{
    root="$(make_fixture)"
    add_migration "$root" postgres 000001 create_users
    add_migration "$root" postgres 000002 thing
    regen_list_fixture "$root"
    commit_all "$root"

    out="$(run "$root" renumber 000002 000001)"; rc=$?
    if [[ $rc -eq 0 ]]; then
        fail "충돌하는 번호로 옮김"
    else
        assert_contains "$out" "000001" && ok
    fi
    rm -rf "$root"
}

CURRENT="apply: 코드에 남은 옛 번호 참조를 보고한다"
{
    root="$(make_fixture)"
    add_migration "$root" postgres 000001 create_users
    add_migration "$root" postgres 000002 our_feature
    regen_list_fixture "$root"
    mkdir -p "$root/server/channels/db"
    printf 'const lastMigration = "000002_upstream_a"\n' > "$root/server/channels/db/ref.go"
    commit_all "$root"
    add_migration "$root" postgres 000002 upstream_a

    out="$(run "$root" apply)"
    assert_contains "$out" "ref.go" && ok
    rm -rf "$root"
}

CURRENT="sync-list: list만 재생성해 verify를 통과시킨다"
{
    root="$(make_fixture)"
    add_migration "$root" postgres 000001 create_users
    regen_list_fixture "$root"
    add_migration "$root" postgres 000002 add_email     # list에 빠진 상태
    commit_all "$root"

    out="$(run "$root" verify)"; rc=$?
    if [[ $rc -eq 0 ]]; then
        fail "사전 조건 실패 — verify가 불일치를 못 잡음"
    else
        run "$root" sync-list >/dev/null
        out="$(run "$root" verify)"; rc=$?
        assert_eq 0 "$rc" "sync-list 후 verify 종료 코드" && ok
    fi
    rm -rf "$root"
}

CURRENT="sync-list: 마이그레이션 파일은 건드리지 않는다"
{
    root="$(make_fixture)"
    add_migration "$root" postgres 000001 create_users
    add_migration "$root" postgres 000002 add_email
    regen_list_fixture "$root"
    commit_all "$root"

    run "$root" sync-list >/dev/null
    assert_file "$root/server/channels/db/migrations/postgres/000001_create_users.up.sql" \
        && assert_file "$root/server/channels/db/migrations/postgres/000002_add_email.up.sql" \
        && ok
    rm -rf "$root"
}

printf '\n통과 %d / 실패 %d\n' "$PASS" "$FAIL"
[[ $FAIL -eq 0 ]]
