// Code generated by mockery v2.53.4. DO NOT EDIT.

// Regenerate this file using `make store-mocks`.

package mocks

import (
	model "github.com/mattermost/mattermost/server/public/model"
	mock "github.com/stretchr/testify/mock"
)

// NotificationHistoryStore is an autogenerated mock type for the NotificationHistoryStore type
type NotificationHistoryStore struct {
	mock.Mock
}

// Delete provides a mock function with given fields: id
func (_m *NotificationHistoryStore) Delete(id string) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteForUser provides a mock function with given fields: userId
func (_m *NotificationHistoryStore) DeleteForUser(userId string) error {
	ret := _m.Called(userId)

	if len(ret) == 0 {
		panic("no return value specified for DeleteForUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(userId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteOlderThan provides a mock function with given fields: timestamp
func (_m *NotificationHistoryStore) DeleteOlderThan(timestamp int64) (int64, error) {
	ret := _m.Called(timestamp)

	if len(ret) == 0 {
		panic("no return value specified for DeleteOlderThan")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(int64) (int64, error)); ok {
		return rf(timestamp)
	}
	if rf, ok := ret.Get(0).(func(int64) int64); ok {
		r0 = rf(timestamp)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(int64) error); ok {
		r1 = rf(timestamp)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Get provides a mock function with given fields: id
func (_m *NotificationHistoryStore) Get(id string) (*model.NotificationHistory, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *model.NotificationHistory
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*model.NotificationHistory, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) *model.NotificationHistory); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.NotificationHistory)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetCountsForUser provides a mock function with given fields: userId
func (_m *NotificationHistoryStore) GetCountsForUser(userId string) (*model.NotificationHistoryCounts, error) {
	ret := _m.Called(userId)

	if len(ret) == 0 {
		panic("no return value specified for GetCountsForUser")
	}

	var r0 *model.NotificationHistoryCounts
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*model.NotificationHistoryCounts, error)); ok {
		return rf(userId)
	}
	if rf, ok := ret.Get(0).(func(string) *model.NotificationHistoryCounts); ok {
		r0 = rf(userId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.NotificationHistoryCounts)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(userId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetForUser provides a mock function with given fields: userId, opts
func (_m *NotificationHistoryStore) GetForUser(userId string, opts model.GetNotificationHistoryOptions) (*model.NotificationHistoryList, error) {
	ret := _m.Called(userId, opts)

	if len(ret) == 0 {
		panic("no return value specified for GetForUser")
	}

	var r0 *model.NotificationHistoryList
	var r1 error
	if rf, ok := ret.Get(0).(func(string, model.GetNotificationHistoryOptions) (*model.NotificationHistoryList, error)); ok {
		return rf(userId, opts)
	}
	if rf, ok := ret.Get(0).(func(string, model.GetNotificationHistoryOptions) *model.NotificationHistoryList); ok {
		r0 = rf(userId, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.NotificationHistoryList)
		}
	}

	if rf, ok := ret.Get(1).(func(string, model.GetNotificationHistoryOptions) error); ok {
		r1 = rf(userId, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MarkAllAsReadForUser provides a mock function with given fields: userId
func (_m *NotificationHistoryStore) MarkAllAsReadForUser(userId string) error {
	ret := _m.Called(userId)

	if len(ret) == 0 {
		panic("no return value specified for MarkAllAsReadForUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(userId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MarkAsRead provides a mock function with given fields: notificationId
func (_m *NotificationHistoryStore) MarkAsRead(notificationId string) error {
	ret := _m.Called(notificationId)

	if len(ret) == 0 {
		panic("no return value specified for MarkAsRead")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(notificationId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MarkAsReadByChannel provides a mock function with given fields: userId, channelId
func (_m *NotificationHistoryStore) MarkAsReadByChannel(userId string, channelId string) error {
	ret := _m.Called(userId, channelId)

	if len(ret) == 0 {
		panic("no return value specified for MarkAsReadByChannel")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(userId, channelId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Save provides a mock function with given fields: notification
func (_m *NotificationHistoryStore) Save(notification *model.NotificationHistory) (*model.NotificationHistory, error) {
	ret := _m.Called(notification)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 *model.NotificationHistory
	var r1 error
	if rf, ok := ret.Get(0).(func(*model.NotificationHistory) (*model.NotificationHistory, error)); ok {
		return rf(notification)
	}
	if rf, ok := ret.Get(0).(func(*model.NotificationHistory) *model.NotificationHistory); ok {
		r0 = rf(notification)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.NotificationHistory)
		}
	}

	if rf, ok := ret.Get(1).(func(*model.NotificationHistory) error); ok {
		r1 = rf(notification)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SaveBatch provides a mock function with given fields: notifications
func (_m *NotificationHistoryStore) SaveBatch(notifications []*model.NotificationHistory) error {
	ret := _m.Called(notifications)

	if len(ret) == 0 {
		panic("no return value specified for SaveBatch")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func([]*model.NotificationHistory) error); ok {
		r0 = rf(notifications)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewNotificationHistoryStore creates a new instance of NotificationHistoryStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewNotificationHistoryStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *NotificationHistoryStore {
	mock := &NotificationHistoryStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
